language: python
python:
  - "3.6"  # 3.6 development branch
  - "3.7"  # 3.7 development branch
  - "3.8"
install:
    - pip install -r requirements.txt
    - pip install .
script:
    pytest tests
services:
  - postgresql
env:
  global:
    - SB_TEST_PGPORT=5432

